// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      stylus: {
        compile: {
          files: {
            'public/css/clonkspot.css': 'css/*.styl'
          }
        }
      },
      watch: {
        stylus: {
          files: 'css/*.styl',
          tasks: 'stylus'
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-stylus');
    return grunt.registerTask('default', 'stylus');
  };

}).call(this);
